# Generated by Django 4.2 on 2025-12-27 16:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(default='bi-activity', max_length=50, verbose_name='Иконка')),
                ('emission_factor_source', models.CharField(blank=True, max_length=200, verbose_name='Источник данных')),
            ],
            options={
                'verbose_name': 'Категория активности',
                'verbose_name_plural': 'Категории активностей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100, verbose_name='Тип активности')),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Количество')),
                ('unit', models.CharField(max_length=20, verbose_name='Единица измерения')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('calculated_co2', models.FloatField(default=0, editable=False, verbose_name='Рассчитанный CO₂ (кг)')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbon_app.activitycategory', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Активность пользователя',
                'verbose_name_plural': 'Активности пользователей',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100, verbose_name='Тип активности')),
                ('co2_per_unit', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='кг CO₂ на единицу')),
                ('unit', models.CharField(max_length=20, verbose_name='Единица измерения')),
                ('region', models.CharField(default='global', max_length=50, verbose_name='Регион')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Источник данных')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbon_app.activitycategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Коэффициент выбросов',
                'verbose_name_plural': 'Коэффициенты выбросов',
                'ordering': ['category', 'activity_type'],
            },
        ),
    ]
