# Generated by Django 4.2 on 2026-01-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(choices=[('transport', '🚗 Транспорт'), ('food', '🍔 Питание'), ('energy', '💡 Энергия'), ('shopping', '🛍️ Покупки'), ('general', '🌍 Общие')], default='general', max_length=20, verbose_name='Категория')),
                ('co2_saving', models.FloatField(default=0, verbose_name='Экономия CO₂ (кг/месяц)')),
                ('difficulty', models.CharField(choices=[('high', 'Высокий приоритет 🔴'), ('medium', 'Средний приоритет 🟡'), ('low', 'Низкий приоритет 🟢')], default='medium', max_length=20, verbose_name='Сложность')),
                ('icon', models.CharField(default='bi-lightbulb', max_length=50, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
                'ordering': ['-co2_saving'],
            },
        ),
    ]
