# Generated by Django 4.2 on 2025-12-27 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок рекомендации')),
                ('description', models.TextField(verbose_name='Подробное описание')),
                ('co2_saving', models.FloatField(default=0, verbose_name='Экономия CO₂ (кг/месяц)')),
                ('difficulty', models.CharField(choices=[('high', 'Высокий приоритет'), ('medium', 'Средний приоритет'), ('low', 'Низкий приоритет')], default='medium', max_length=20, verbose_name='Сложность внедрения')),
                ('is_general', models.BooleanField(default=True, verbose_name='Общая рекомендация')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carbon_app.activitycategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
                'ordering': ['-co2_saving'],
            },
        ),
    ]
