# Generated by Django 4.2 on 2026-01-04 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carbon_app', '0002_recommendation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={},
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='co2_saving',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='difficulty',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='icon',
            field=models.CharField(default='lightbulb', max_length=50),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbon_app.recommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'recommendation')},
            },
        ),
    ]
