# Generated by Django 4.2 on 2026-01-04 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carbon_app', '0003_alter_recommendation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrecommendation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Рекомендация пользователя', 'verbose_name_plural': 'Рекомендации пользователей'},
        ),
        migrations.AlterUniqueTogether(
            name='userrecommendation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='is_applied',
            field=models.BooleanField(default=False, verbose_name='Применено'),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='is_viewed',
            field=models.BooleanField(default=False, verbose_name='Просмотрено'),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbon_app.recommendation', verbose_name='Рекомендация'),
        ),
        migrations.AlterField(
            model_name='userrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
