# Generated by Django 4.2 on 2026-01-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_app', '0004_alter_userrecommendation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-co2_saving'], 'verbose_name': 'Рекомендация', 'verbose_name_plural': 'Рекомендации'},
        ),
        migrations.AddField(
            model_name='recommendation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='category',
            field=models.CharField(choices=[('transport', '🚗 Транспорт'), ('food', '🍔 Питание'), ('energy', '💡 Энергия'), ('shopping', '🛍️ Покупки'), ('general', '🌍 Общие')], default='general', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='co2_saving',
            field=models.FloatField(default=0, verbose_name='Экономия CO₂ (кг/месяц)'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='difficulty',
            field=models.CharField(choices=[('high', 'Высокий приоритет 🔴'), ('medium', 'Средний приоритет 🟡'), ('low', 'Низкий приоритет 🟢')], default='medium', max_length=20, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='icon',
            field=models.CharField(default='bi-lightbulb', max_length=50, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
